version: '3'

services:
  db:
    image: postgres:14
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
      - ./docker/scripts:/docker-entrypoint-initdb.d # この行を追加しただけ
    environment:
      - POSTGRES_PASSWORD=postgres
    restart: always
volumes:
  db-store:
