version: '3'

services:
  db:
    image: postgres:14
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
      - ./docker/scripts:/docker-entrypoint-initdb.d # この行を追加しただけ
    environment:
      - POSTGRES_PASSWORD=postgres
    restart: always
  nginx:
    image: nginx:latest
    container_name: nginx
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8443:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/logs:/var/log/nginx
      - ./dist/apps/todo-app:/usr/share/nginx/html
volumes:
  db-store:
